### ISSUE TITLE
No error handlers are registeres, logging exception

### ISSUE THREAD

**Issue by dcorreavi** [dzakyputra/doggobot#5]
Hi! Thanks for this cool Bot. However, I'm getting the following error:

**No error handlers are registered, logging exception.**

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/Users/dcorreavi/Dev/woofbot/main.py", line 12, in bop
    allowed_extension = ['jpg','jpeg','png']
AttributeError: 'CallbackContext' object has no attribute 'message'

**Comment by dzakyputra** [comment]
Hi, I am pretty sure that's because of the version of python-telegram-bot

You can try this method and see if it works --> https://stackoverflow.com/questions/60804083/python-telegram-bot-error-callbackcontext-object-has-no-attribute-message

**Comment by dcorreavi** [comment]
Hi! That worked. Thanks!
